#!/bin/bash

echo ""
echo "=== Django backend (run in one terminal) ==="
echo "cd backend"
echo "python manage.py runserver 8000"
echo ""
echo "=== React frontend (run in another terminal) ==="
echo "cd frontend/src"
echo "npm run dev -- --port 5173"
echo ""
echo "=== Expose backend with localhost.run (third terminal) ==="
echo "ssh -R 80:localhost:8000 localhost.run"
echo ""
echo "=== Expose frontend with localhost.run (fourth terminal) ==="
echo "ssh -R 80:localhost:5173 localhost.run"
echo ""
echo "Open the URLs provided by localhost.run for sharing!"
echo ""
