# Generated by Django 5.2.1 on 2025-07-21 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0002_alter_molecule_category_alter_molecule_name_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="molecule",
            old_name="quanitity",
            new_name="quantity",
        ),
    ]
