# Generated by Django 5.2.4 on 2025-10-07 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0003_rename_quanitity_molecule_quantity"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="last_updated",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="molecule",
            name="quantity",
            field=models.CharField(blank=True, null=True),
        ),
    ]
