# Generated by Django 5.2.4 on 2025-10-07 16:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0004_project_last_updated_alter_molecule_quantity"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="project",
            constraint=models.UniqueConstraint(
                fields=("user", "name"), name="uniq_project_user_name"
            ),
        ),
    ]
