# Generated by Django 5.2.4 on 2026-02-17 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0005_project_uniq_project_user_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="molecule",
            name="extra_data",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
