# Generated by Django 5.2.4 on 2026-02-17 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0006_molecule_extra_data"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="molecule",
            name="category",
        ),
        migrations.RemoveField(
            model_name="molecule",
            name="name",
        ),
        migrations.RemoveField(
            model_name="molecule",
            name="quantity",
        ),
    ]
