# Generated by Django 5.2.4 on 2026-02-19 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0007_remove_molecule_category_remove_molecule_name_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="molecule",
            options={"ordering": ["order"]},
        ),
        migrations.AddField(
            model_name="molecule",
            name="order",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
